### ISSUE TITLE
User access control

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens#10]
Would it be a good idea to have user's only able to access a subset of screens?

For example:
Admins can access any screen.
Communications department can access public screens.
Development teams can access their own screens.

**Comment by railsagainstignorance** [comment]
possibilities: 
- make the full admin view obscure and/or access whitelisted, http://ftlabs-screens.herokuapp.com/admin/all
- make it possible to join straight into an admin group, e.g. http://ftlabs-screens.herokuapp.com/viewer/TeamName
  - can use the url to override the current settings of a viewer
  - and to admin it: http://ftlabs-screens.herokuapp.com/admin/TeamName
- have a default group of not-in-a-team, which is a bit of a wild west, everyone-sees-everyone-else kind of thing
- ...

**Comment by triblondon** [comment]
Research needed here: can we use S3O to piggyback on AD groups?  I do not want to create a new groups tool.

**Comment by lucas42** [comment]
s3o currently doesn't support this.  However, there's a feature request for it: https://jira.ft.com/browse/SEC-272
Please can you comment on that ticket so that:
a) it gets prioritised, and
b) you can have input into what the interface looks like (eg does s3o handle the authorisation itself, or just return enough information to allow the app to handle this?)

**Comment by JakeChampion** [comment]
We now have an audit log available at `/logs`
