### ISSUE TITLE
screen id collisions could be nasty

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/screens#43]
Currently, ids are assigned at random, from a rage 1-99999.
Collisions are unlikely, but inevitable.
We should handle them a bit better.

Context:
- The server has no state/memory, so everything has to be negotiated dynamically.
- If a viewer is down/off, it only persists in the greyed out memory of any browsers currently showing the admin page
- If a viewer is live, its id is known to the server, so any new ids generated can be guarantee not to collide with it
- a viewer's details are persisted in its local storage.
- the main situation to handle is when an existing viewer (viewer1) is down, and a new viewer (viewer2) starts up and is handed viewer1's id, and then viewer1 wakes up again whilst viewer2 is live.

Proposal 1:
- we store length of ownership (of the id) in the viewer
- if two viewers are live with the same id, the server compares the ages, leaves the older viewer (viewer1) unchanged, and triggers a change of id in the younger viewer (viewer2).
- this id change should happen seamlessly, without need for human intervention, and should retain the text name and list of content for the newly-ided viewer
- the admin screen should probably display a note to the effect that the id of the viewer has changed, in case the owner had paid attention and written it down somewhere. e.g. (#42337 was #87564)

**Comment by JakeChampion** [comment]
Some more proposals:
- We create an ID generation service which ensures no collisions by using a seeded random number iterator (seeded to ensure that a reboot of the service stills have the same sequence of numbers generated).
- We create an ID generation function that accepts variables from the computer the viewer is running on (mac address etc) and using those variables in the generation.
- Have the server hold a database of all IDs and get new screens to ping the server to check if their ID is already in use.

**Comment by JakeChampion** [comment]
@railsagainstignorance I like your proposal :+1:

**Comment by seanmtracey** [comment]
The second suggestion would be more robust than the current implementation, but still allows for conflict. If we maintain a list of assigned IDs and run the checks as Chris suggests, we can ensure that any conflicts are handled intelligently, rather than through probabilities. That said, I do find your first suggestion interesting, Jake - but I'm not sure I'd be the one/know how to implement it.

**Comment by JakeChampion** [comment]
@seanmtracey Here is a first-pass implementation of a resumable seeded random number generator -- https://tonicdev.com/jakechampion/random-number-generator

The idea being that you store the iteration count in some external resource and upon starting the server up, you pass the stored iteration count to the random number generator so that it can pick up from where it left off.

**Comment by JakeChampion** [comment]
Resolved by #59
